/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DbStock;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Articles;
import model.EtatStock;
import model.Stock;

/**
 *
 * @author mamadoumbayedione
 */
public class ViewEditArticle extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditArticle
     */
    public ViewEditArticle() {
        initComponents();
         DbStock db = new DbStock();
        setLocationRelativeTo(null);
        setResizable(false);
        //mettre la categorie correspondante
        String genre = "";
        cCategorie.removeAllItems();
        db.listeCategorie(cCategorie,genre);
        loadAllArticles();
        String fournisseur = "";
       //cFournisseur.removeAllItems();
        db.listeFournisseur1(cFournisseur);
                //,fournisseur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTArticle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQuantite = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbMan = new javax.swing.JRadioButton();
        rbWoman = new javax.swing.JRadioButton();
        rbUnisex2 = new javax.swing.JRadioButton();
        cCategorie = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cFournisseur = new javax.swing.JComboBox();
        txtDesignation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPrixU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Editer Article");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-file-96.png"))); // NOI18N

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-google-web-search-32.png"))); // NOI18N
        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom Article", "Designation", "Quantite", "Prix Unitaire", "Prix Total", "Nom Categorie", "Nom Fournisseur"
            }
        ));
        jTArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTArticleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTArticle);

        jLabel3.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel3.setText("ID:");

        textID.setEditable(false);
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-property-32.png"))); // NOI18N
        btnUpdate.setText("Modifier");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-32.png"))); // NOI18N
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-quit-32.png"))); // NOI18N
        btnQuit.setText("Quitter");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel5.setText("Quantite: ");

        txtQuantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantiteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel8.setText("Nom Article: ");

        txtLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibelleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel7.setText("Genre: ");

        buttonGroup1.add(rbMan);
        rbMan.setText("Homme");
        rbMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbWoman);
        rbWoman.setText("Femme");
        rbWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWomanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbUnisex2);
        rbUnisex2.setText("Unisex");
        rbUnisex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUnisex2ActionPerformed(evt);
            }
        });

        cCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCategorieActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel6.setText("Categorie: ");

        jLabel9.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel9.setText("Fournisseur: ");

        cFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFournisseurActionPerformed(evt);
            }
        });

        txtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesignationActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel10.setText("Designation: ");

        jLabel11.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel11.setText("Prix Unitaire: ");

        txtPrixU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbUnisex2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cFournisseur, 0, 170, Short.MAX_VALUE)
                                    .addComponent(txtPrixU))))
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLibelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rbMan)
                    .addComponent(rbWoman)
                    .addComponent(rbUnisex2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(cCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrixU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnQuit))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() ==java.awt.event.KeyEvent.VK_ENTER )
        {

            search();
        }
    }//GEN-LAST:event_txtSearchKeyPressed
  //chargement des articles
    public void loadAllArticles(){
        dftm = new DefaultTableModel();
         //indiquer les valeurs de l'entete
         dftm.setColumnIdentifiers(tab);
         
         
         DbStock db = new DbStock();
         db.loadArticle(dftm, jTArticle);
    }
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (txtSearch.getText().toString().trim().length()>=2) {
            btnSearch.doClick();
        }
        else if(txtSearch.getText().toString().trim().length()==0){
            btnSearch.doClick();
        }
    }//GEN-LAST:event_txtSearchKeyReleased
 private String[] tab = {"ID", "Nom","Designation","Quantite","Prix Unitaire","Prix Total","nomCategorie","nomFournisseur"};
    private DefaultTableModel dftm;
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnSearchActionPerformed
private void search(){
    //initialiser
        dftm = new DefaultTableModel();
        //indiquer les valeurs de l'entete
        dftm.setColumnIdentifiers(tab);
        //creation objet
        DbStock db = new DbStock();
        //rechercher  par le libelle
        String libelle  = txtSearch.getText().trim();
        if(libelle.equals(""))

        db.loadArticle(dftm, jTArticle);
        else
        db.loadArticleByName(dftm, jTArticle, libelle);
}
    private void jTArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTArticleMouseClicked
        // TODO add your handling code here:
        //tab = {"ID", "Nom","Designation","Quantite","Prix Unitaire","Prix Total","nomCategorie","nomFournisseur"}
        DbStock db = new DbStock();// cFournisseur.removeAllItems();
        int ligne =jTArticle.getSelectedRow();
        //inserer la ligne selectionnee dans la partie a editer
        String id = jTArticle.getValueAt(ligne, 0).toString();
        textID.setText(id);
        String libelle = jTArticle.getValueAt(ligne, 1).toString();
        txtLibelle.setText(libelle);
        String qte = jTArticle.getValueAt(ligne, 3).toString();
        txtQuantite.setText(qte);
        String designation = jTArticle.getValueAt(ligne, 2).toString();
        txtDesignation.setText(designation);
        String prixU = jTArticle.getValueAt(ligne, 4).toString();
        txtPrixU.setText(prixU);
        String nomCategorie = jTArticle.getValueAt(ligne, 6).toString();
        cCategorie.setSelectedItem(nomCategorie);
        
        String fournisseur = jTArticle.getValueAt(ligne, 7).toString();
        
        cFournisseur.setSelectedItem(fournisseur);
       cFournisseur.removeAllItems();
                
        db.listeFournisseur(cFournisseur,fournisseur);
        //cFournisseur.setSelectedItem(""+fournisseur);
        
               
        
        String genre = db.genreCategorie(nomCategorie);
        
        if (genre.startsWith("H"))
        {
            rbMan.setSelected(true);
            
        }
        else
        {
            if(genre.startsWith("U"))
            {
                rbUnisex2.setSelected(true);
            }
            else{
                 rbWoman.setSelected(true);
            }
 
           
        }
 
        
        
     

    }//GEN-LAST:event_jTArticleMouseClicked

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Articles article = new Articles();
        DbStock db = new DbStock();
        
        //Modifier La categorie
        String libelle = txtLibelle.getText().trim();
        String designation = txtDesignation.getText().trim();
        
        String categorie =cCategorie.getSelectedItem().toString();
        String fournisseur = cFournisseur.getSelectedItem().toString();
        int qte = Integer.parseInt(txtQuantite.getText().trim());
        int prixU = Integer.parseInt(txtPrixU.getText().trim());
        int prixT = qte*prixU;
         

        int  idCategorie ;
        int idFournisseur;
        
        
               

        //recuperer l'article

        int id = Integer.parseInt(textID.getText().trim());
        article.setNomArticle(libelle);
        article.setDesignation(designation);
        //enregistrer idcategorie dans le model article
        idCategorie = db.idCategorie(categorie);
        article.setIdCtegorie(idCategorie);
        article.setQte(qte);
        article.setPrixT(prixT);
        article.setPrixU(prixU);
        
        idFournisseur = db.idFournisseur(fournisseur);
        
        
        article.setIdFournisseur(idFournisseur);
        article.setIdArticle(id);
        int idArticle;
        
        

        
        boolean b = db.updateArticle(article);
        

        if(b){
            
            
             //enregistre entree stock dans la table stock
            idArticle = db.loadidArticle();
            //appel de la table stock, ajouter la quantite
           Stock stock = new Stock();
           stock.setNomArticle(libelle);
           stock.setMontantStock(prixT);
           stock.setQteStock(qte);
           boolean a = db.saveStock(stock);
           
           int idEstock = db.idEStockArticle(libelle);
            EtatStock etatstock = new EtatStock();
            etatstock.setIdEStock(idEstock);
            etatstock.setMontantEStock(prixT);
            etatstock.setNomEArticle(libelle);
            etatstock.setQteEStock(qte);
            boolean c = db.updateEStock(etatstock);
           if(a && c){
                          //pour afficher a l'ecran
                       JOptionPane.showMessageDialog(this, "SUCCESS! Article " +libelle+ " modifie dans la categorie " +categorie);


           }
            
            //reinitialiser les donnees
            loadAllArticles();
            
            //enregistre entree stock dans la table stock
            idArticle = db.loadidArticle();
            //appel de la table stock, ajouter la quantite
            //cree la quantite du stock
            
            txtLibelle.setText("");
            
            txtDesignation.setText("");
            txtQuantite.setText("");
            txtPrixU.setText("");
        }    
        else{
            JOptionPane.showMessageDialog(this, "ERROR! Article  non modifié");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        String id = textID.getText();

        if (id.equals("")==false)
        {
            DbStock db = new DbStock();
            int idInt =Integer.parseInt(id);
             String nomArticle =db.nomArticle(idInt);
            int idEStock = db.idEStockArticle(nomArticle);
            
            int choice = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'article "+txtLibelle.getText()+" ?", "Message",JOptionPane.YES_NO_OPTION);
            if (choice ==JOptionPane.YES_OPTION)
            {
                boolean b = db.deleteArticle(idInt);
               
                // appel rechargement des articles

                if (b)
                {
                     
                        //enregistre sortie stock dans la table stock
                     Stock stock = new Stock();
                     stock.setNomArticle(nomArticle);
                     stock.setMontantStock(0);
                     stock.setQteStock(0);
                     boolean c = db.saveStock(stock);
                    
                        boolean a = db.deleteEStock(idEStock);
                        //if(a){
                          //pour afficher a l'ecran
                                 JOptionPane.showMessageDialog(this, "SUCCESS! Article "+txtLibelle.getText()+" supprimé");
   
                    txtLibelle.setText("");
                    txtPrixU.setText("");
                    rbMan.setSelected(false);
                    rbWoman.setSelected(false);
                    textID.setText("");
                    txtDesignation.setText("");
                    txtQuantite.setText("");
                    loadAllArticles();
                //}
                }
                else{
                    JOptionPane.showMessageDialog(this,"article non supprimé. Verifier si la commande de cet article a été supprimé");
                }
            }
            
                else
                {
                    JOptionPane.showMessageDialog(this, "article non supprimé");
                }
        }
                        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void txtQuantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantiteActionPerformed

    private void txtLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibelleActionPerformed

    private void rbManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManActionPerformed
        // TODO add your handling code here:
        DbStock db = new DbStock();
        String gender ="Homme";
        cCategorie.removeAllItems();
        db.listeCategorie(cCategorie,gender);
    }//GEN-LAST:event_rbManActionPerformed

    private void rbUnisex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUnisex2ActionPerformed
        // TODO add your handling code here:
                DbStock db = new DbStock();
        String gender ="Unisex";
        cCategorie.removeAllItems();
        db.listeCategorie(cCategorie,gender);
    }//GEN-LAST:event_rbUnisex2ActionPerformed

    private void cFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cFournisseurActionPerformed

    private void txtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesignationActionPerformed

    private void cCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategorieActionPerformed

    private void rbWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWomanActionPerformed
        // TODO add your handling code here:
                DbStock db = new DbStock();
        String gender ="Femme";
        cCategorie.removeAllItems();
        db.listeCategorie(cCategorie,gender);
    }//GEN-LAST:event_rbWomanActionPerformed

    private void txtPrixUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditArticle().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cCategorie;
    private javax.swing.JComboBox cFournisseur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTArticle;
    private javax.swing.JRadioButton rbMan;
    private javax.swing.JRadioButton rbUnisex2;
    private javax.swing.JRadioButton rbWoman;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtPrixU;
    private javax.swing.JTextField txtQuantite;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
